### ISSUE TITLE
Error from getting news

### ISSUE THREAD

**Issue by Lenny12311212** [djlorenzouasset/Cosmetics-Generator#7]
![image](https://github.com/djlorenzouasset/Cosmetics-Generator/assets/142605298/66af600f-3ed1-4919-84f3-f1c29733b51c)

**Comment by djlorenzouasset** [comment]
andre fix it and open a pull so I can merge it

**Comment by djlorenzouasset** [comment]
my

**Comment by djlorenzouasset** [comment]
why

**Comment by djlorenzouasset** [comment]
why

**Comment by djlorenzouasset** [comment]
fixed at commit https://github.com/djlorenzouasset/Cosmetics-Generator/commit/1cabc7aa3d443e5426ab4c158e1511efc9c4fe07
